### ISSUE TITLE
Current master branch is ahead of latest tag v0.2.2

### ISSUE THREAD

**Issue by vgallissot** [sbani/ansible-role-liquidprompt#6]
Hi,

Tag v0.2.2 refers to a version where RedHat stuff were handled via /etc/bashrc.
You removed that part (thanks) but there is no tag associated with that new release.

Can you make one ?
Like v0.3 or so.

Thanks,
Vincent

**Comment by sbani** [comment]
Thanks for the info. I updated the git tag to 0.2.3 (because it's a bug fix release).
Hope you are ok with that.

**Comment by vgallissot** [comment]
OK, nice
